### PR TITLE
fixes to make tiptop work on macOS

### LINKED ISSUE #6: temperature unavailable on macOS
Hi! This looks like a nice little tool, I discovered earlier when @willmcgugan retweeted your announcement.

I just tried running it on macOS and ran into a couple issues (PR with quick fixes incoming), but one of them seems to be bigger than the rest, which is the butchered temperature situation on macOS.

This is a known problem (see [this](https://stackoverflow.com/questions/2440511/getting-cpu-temperature-using-python) and [this](https://www.reddit.com/r/learnpython/comments/bjulew/mac_os_get_cpu_temp_with_python/) for a non-exhaustive description of the issue, but it comes down to `psutil.sensors_temperatures()` being unavailable in the macOS version of the `psutil` package, which trips over the following line:

https://github.com/nschloe/tiptop/blob/76d3f299988881c352fc7bc3c4b90cb32ac399d1/src/tiptop/_cpu.py#L56

I am adding a quick fix for now but since the temp graph in tiptop is so neat it would probably be worth the effort to find a functionally usable workaround for this as well.

### PR DESCRIPTION
**Pull request by jkbecker**
These are just some basic fixes and a WIP, not ready for merging yet.

Turns out some neat features have to be solved differently for macOS specifically, or are specifically Linux-only, which will make them either go missing or have weird values on non-Linux OSes.

Fixes #6.

### CODE REVIEW

**Comment by jkbecker** [comment]
Screenshot 2021-11-13 at 20 06 26
 
The changes above result in this runtime behavior - it's definitely suboptimal because some crucial information is missing, but I believe this can be added by looking into how glances gets these values (for example). Without these changes, none of the panels are able to run, as there are exceptions thrown in `_cpu.py`, `_mem.py`, `_info.py`, and `_proc_list.py`.

**Comment by nschloe** [comment]
I'd already merge it now because the PR adds functionality and removes nothing, but let me know when you yourself are happy with it.

**Comment by jkbecker** [comment]
Sure, maybe that's a good idea - I can't promise that I'll be able to work on any of the more extensive fixes any time soon, so it's probably better to not hold this here artificially if you're ok with the changes.

**Comment by nschloe** [comment]
I've now merged a bunch of PRs which should fix _most_ (?) of the issues. Could you try again with v0.0.6?

**Comment by jkbecker** [comment]
All merged changes are an improvement except for the memory change

```python
        values = [mem.used, mem.available, mem.cached if hasattr(mem, 'cached') else 0, mem.free]
```

which seems to be reverted in the other PRs. Should I add it back or do you prefer a different way of mitigating this?

**Comment by nschloe** [comment]
This is handled differently now.

**Comment by jkbecker** [comment]
Ah, I see what you were doing there... it's missing the values, which still break. Fix coming up, I think that should be it then.

**Comment by nschloe** [comment]
A more fitting fix is in #18.

**Comment by nschloe** [comment]
I think all of the issues here are fixed now.

**Pull request closed without merging**
